name: CI
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
  merge_group:
    types:
      - checks_requested

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NPM registry authentication & install dependencies
        uses: ./.github/actions/setup
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACTIONS_PACKAGES_DOWNLOAD_TOKEN }}

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typecheck

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup
  #       uses: ./.github/actions/setup

  #     - name: Run unit tests
  #       run: yarn test --maxWorkers=2 --coverage

  build-package:
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NPM registry authentication & install dependencies
        uses: ./.github/actions/setup
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build package
        run: npm publish

  # build-web:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup
  #       uses: ./.github/actions/setup

  #     - name: Build example for Web
  #       run: |
  #         yarn example expo export --platform web
