name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NPM registry authentication & install dependencies
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typecheck

  build-package:
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NPM registry authentication & install dependencies
        uses: ./.github/actions/setup

      - name: Build package
        run: npm publish

      - name: Create release
        run: |
          echo "Creating release for tag: ${{ github.ref_name }}"
          gh release create ${{ github.ref_name }} --title "${{ github.ref_name }}" -F ./.github/release/RELEASE_NOTES.md
        env:
          GH_TOKEN: ${{ github.token }}
